2024-02-18 06:03:11,681 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2024-02-18 06:03:11,682 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /home/codespace/.python/current/lib/python3.10/site-packages/instabot/bot/bot.py
2024-02-18 06:03:11,682 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2024-02-18 06:03:12,436 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2024-02-18 06:03:12,919 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2024-02-18 06:03:13,455 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2024-02-18 06:03:13,893 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2024-02-18 06:03:13,893 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2024-02-18 06:03:13,893 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2024-02-18 06:03:13,894 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
